export const ROUTES = {
  HOME: "/",
  PRO: "/pro",
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY_EMAIL: "/verify-email",
  COMPLETE_PROFILE: "/complete-profile",
  PENDING_VERIFICATION: "/pending-verification",
  DASHBOARD: "/dashboard",
  MESSAGES: "/messages",
  PROFILE: "/profile",
  EDIT_PROFILE: "/profile/edit",
  RESUME_UPLOAD: "/profile/resume",
  PROJECTS: "/projects",
  PROJECT_DETAILS: "/projects/:id",
  MY_PROJECTS: "/my-projects",
  POST_PROJECT: "/post-project",
  APPLICANTS_LIST: "/recruiter/applicants",
  SELECT_FREELANCER: "/recruiter/select-freelancer",
  TALENT_SOLUTIONS: "/talent-solutions",
  COMPANY_INFO: "/company-info",
  ADMIN: "/admin",
  ADMIN_ACCEPT_INVITE: "/admin/accept-invite",
  STATEMENT: "/statement",
  CAREER_AUTOPILOT: "/career-autopilot",
  PROJECT_AUTOPILOT: "/post-project/autopilot",
  PROJECT_VAULT: "/projects/:id/vault",
  GENERAL_PROJECT_VAULT: "/project-vault",
  COMPANY_WORKSPACE: "/company-workspace",
  INCOME_OS: "/income-os",
  BUSINESS_OS: "/business-os",
  SECURITY_CENTER: "/security-center",
  ECOSYSTEM_DASHBOARD: "/ecosystem-dashboard",
};

